// Github Rustyribcage
// This indicator is written in pinescript code and is designed to be used in tradingview.com to overlay the DXY (Dollar Index) on the chart.
// It normalizes the DXY data to fit within the range [0, 1] and calculates a 15-bar average.
// It also provides alerts for significant changes in the DXY state, indicating hawkish or dovish conditions.
// Many traders realize the importance of understanding what the dollar is doing since everything is measured 
// in dollars. So if this indicator is high, it is bearish, not bullish! I color coded it so that it was a bit 
// more intuitive to understand.
// @version=5
indicator("Favorable DXY Overlay", overlay = false)

// Define the symbol for the DXY (Dollar Index) chart
dxySymbol = "DXY"

// Fetch DXY data using the security function
dxyClose = request.security(dxySymbol, "D", close)

// Calculate the minimum and maximum values of DXY data
dxyMin = ta.lowest(dxyClose, 50)
dxyMax = ta.highest(dxyClose, 50)

// Normalize the DXY data to fit within the range [0, 1]
normalizedDXY = (dxyClose - dxyMin) / (dxyMax - dxyMin)

// Function to calculate the average of a series over a specified period
avgSeries(source, length) =>
    sum = 0.0
    for i = 0 to length - 1
        sum := sum + source[i]
    sum / length

// Calculate the 5-bar average of normalizedDXY
averageNormalizedDXY = avgSeries(normalizedDXY, 15)

// Initialize variables so that it only alerts me when there is change.
var bool prevHawkishDXYAlert = false
var bool prevDovishDXYAlert = false

// Labeling DXY extremes. > >= ? < or <= ? seems to not effect anything. Use these more throughout the script.
hawkishDXY = normalizedDXY < 1 and averageNormalizedDXY < 1
dovishDXY = normalizedDXY > 0 and averageNormalizedDXY > 0 
nonUltraHawkishDXY = normalizedDXY <= 0.9 and averageNormalizedDXY <= 0.9
nonUltraDovishDXY = normalizedDXY >= 0.1 and averageNormalizedDXY >= 0.1

hawkishDXYAlert = normalizedDXY < 0.5 and averageNormalizedDXY < 0.5
dovishDXYAlert = normalizedDXY > 0.5 and averageNormalizedDXY >0.5

// Check for state change and trigger alerts
if hawkishDXYAlert != prevHawkishDXYAlert
    alert(message="Hawkish DXY above 0.5")
    prevHawkishDXYAlert := hawkishDXYAlert

if dovishDXYAlert != prevDovishDXYAlert
    alert(message="Dovish DXY below 0.5")
    prevDovishDXYAlert := dovishDXYAlert

colorDovish = color.green
colorHawkish = color.red

// Set the transparency for the colors
transparency = 50

// Plot the 5-bar average of normalized DXY data
plot(averageNormalizedDXY, title="15-Bar Avg Normalized DXY", color=averageNormalizedDXY >= 0.5 ? colorHawkish : colorDovish, linewidth=2, transp=transparency)

// Plot the normalized and color coded data DXY data
plot(normalizedDXY, title = "Normalized DXY", color = normalizedDXY >= 0.5 ? colorHawkish : colorDovish, linewidth = 2, transp = transparency)


alertcondition(normalizedDXY < 0.5 and averageNormalizedDXY < 0.5, title = "DXY Below 0.5", message = "Dovish DXY is Below 0.5!")
alertcondition(normalizedDXY > 0.5 and averageNormalizedDXY >0.5, title = "DXY Above 0.5", message = "Hawkish DXY is Above 0.5!")
